---
openapi: 3.0.1
info:
  title: Authors API
  version: v1
paths:
  "/authors":
    get:
      summary: Retrieves all authors
      tags:
      - Authors
      responses:
        '200':
          description: authors retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/author"
    post:
      summary: Creates an author
      tags:
      - Authors
      parameters: []
      responses:
        '201':
          description: author created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/authors/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Retrieves an author
      tags:
      - Authors
      responses:
        '200':
          description: author retrieved
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/author"
        '404':
          description: author not found
    patch:
      summary: Updates an author
      tags:
      - Authors
      parameters: []
      responses:
        '200':
          description: author updated
        '404':
          description: author not found
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: Deletes an author
      tags:
      - Authors
      responses:
        '204':
          description: author deleted
        '404':
          description: author not found
  "/competencies":
    get:
      summary: Retrieves all competencies
      tags:
      - Competencies
      responses:
        '200':
          description: competencies found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Competency"
    post:
      summary: Creates a competency
      tags:
      - Competencies
      parameters: []
      responses:
        '201':
          description: competency created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Competency"
  "/competencies/{id}":
    get:
      summary: Retrieves a competency
      tags:
      - Competencies
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: competency found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Competency"
        '404':
          description: competency not found
    patch:
      summary: Updates a competency
      tags:
      - Competencies
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: competency updated
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Competency"
    delete:
      summary: Deletes a competency
      tags:
      - Competencies
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: competency deleted
        '404':
          description: competency not found
  "/courses":
    get:
      summary: Retrieves all courses
      tags:
      - Courses
      responses:
        '200':
          description: courses found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/course"
    post:
      summary: Creates a course
      tags:
      - Courses
      parameters: []
      responses:
        '201':
          description: course created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/course"
  "/courses/{id}":
    get:
      summary: Retrieves a course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: course found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/course"
    patch:
      summary: Updates a course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: course updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                author_id:
                  type: integer
    delete:
      summary: Deletes a course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: course deleted
components:
  schemas:
    course:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Course Title
        description:
          type: string
          example: Course Description
        author_id:
          type: integer
          example: 1
      required:
      - title
      - description
      - author_id
    Competency:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
      - id
      - name
    author:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
      - id
      - name
