default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5499
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: financial_education_development

test:
  <<: *default
  database: financial_education_test

production:
  <<: *default
  database: financial_education_production
  username: financial_education
  password: <%= ENV["FINANCIAL_EDUCATION_DATABASE_PASSWORD"] %>
